spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8083/
          predicates:
            - Path=/user/**
        - id: bid
          uri: http://localhost:8082/
          predicates:
            - Path=/bid/**
        - id: item
          uri: http://localhost:8081/
          predicates:
            - Path=/item/**