spring:
  cloud:
    gateway:
      routes:
        - id: USERMS
          uri: lb://USERMS
          predicates:
            - Path=/user/**
        - id: BIDMS
          uri: lb://BIDMS
          predicates:
            - Path=/bid/**
        - id: ITEMMS
          uri: lb://ITEMMS
          predicates:
            - Path=/item/**